# Generated by Django 2.1.4 on 2019-01-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0002_auto_20190109_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.CharField(blank=True, choices=[('0', 'Angry'), ('1', 'Happy'), ('2', 'Excited'), ('3', 'Sad')], max_length=15, null=True, verbose_name='How do you feel?'),
        ),
    ]
