# Generated by Django 2.1.4 on 2019-01-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0004_auto_20190116_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='feeling',
            field=models.CharField(blank=True, choices=[('0', 'Angry'), ('1', 'Happy'), ('2', 'Excited'), ('3', 'Sad'), ('LOVE', 'Love'), ('SATISFIED', 'Satisfied'), ('MAD', 'Mad'), ('TIRED', 'Tired'), ('SURPRISED', 'Surprised'), ('AFRAID', 'Afraid')], help_text='How do you feel?', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='diary',
            name='is_commentable',
            field=models.CharField(choices=[('all', 'All'), ('no_one', 'No One')], default='all', help_text='Who can comment on this diary?', max_length=7),
        ),
        migrations.AlterField(
            model_name='diary',
            name='is_visible',
            field=models.CharField(choices=[('all', 'All'), ('no_one', 'No One')], default='all', help_text='Who can see this diary?', max_length=7),
        ),
    ]
