# Generated by Django 2.1.4 on 2019-02-20 14:00

from django.db import migrations


def set_likes_and_comments_count(apps, schema_editor):
    Diary = apps.get_model('diaries', 'Diary')
    DiaryLike = apps.get_model('diaries', 'DiaryLike')
    for d in Diary.objects.all():
        likes_count = DiaryLike.objects.filter(diary=d).count()
        d.likes_count = likes_count
        d.comments_count = d.comments.count()
        d.save()


def reset_likes_and_comments_count(apps, schema_editor):
    Diary = apps.get_model('diaries', 'Diary')
    for d in Diary.objects.all():
        d.likes_count = 0
        d.comments_count = 0
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0006_auto_20190220_1307'),
    ]

    operations = [
        migrations.RunPython(
            set_likes_and_comments_count,
            reset_likes_and_comments_count
        )
    ]
