# Generated by Django 2.1.4 on 2019-01-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190115_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, help_text='Describe yourself in less than 255 character.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, help_text="If you don't provide one. your username will be used", max_length=63),
        ),
    ]
