# Generated by Django 2.2.9 on 2020-01-09 15:25
from django.db import migrations

from ..utils import assign_default_image_to_profile


def assign_default_image_to_profiles_without_one(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    for profile in Profile.objects.all():
        if not profile.image:
            profile = assign_default_image_to_profile(profile)
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190116_1753'),
    ]

    operations = [
        migrations.RunPython(
            assign_default_image_to_profiles_without_one,
            migrations.RunPython.noop
        )
    ]
